services:
  redis:
    image: redis:8-bookworm
    networks:
      - redis
    expose:
      - "6379"
  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring
  market_data:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BIN_NAME: market_data
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - monitoring
      - redis
    expose:
      - "9090"
  arb_engine:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BIN_NAME: arb_engine
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - monitoring
      - redis
    expose:
      - "9090"
  executor:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BIN_NAME: executor
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - monitoring
      - redis
    expose:
      - "9090"

volumes:
  prometheus_data:
  grafana_data:
networks:
  monitoring:
    driver: bridge
  redis:
    driver: bridge