[package]
name = "market_data"
version = "0.1.0"
edition.workspace = true

[dependencies]
shared_types = {path = "../shared_types"}
binance_connector = {path = "../binance_connector"}
utils = {path = "../utils"}

serde.workspace = true
tokio.workspace = true
tokio-util.workspace = true
anyhow.workspace = true
rust_decimal.workspace = true
dotenvy.workspace = true
once_cell.workspace = true
serde_json.workspace = true
tracing.workspace = true
redis.workspace = true
metrics.workspace = true
futures-util.workspace = true

tokio-tungstenite = { version = "0.23.0"} # use 0.23.0 because binance_spot_connector_rust
backoff = { version = "0.4.0", features = ["tokio"] }
binance_spot_connector_rust = { version = "1.3.0", features = ["enable-hyper", "enable-tokio-tungstenite"]}

